<message>
    <message-header>
        <message-id>str1234</message-id>
        <transaction-name>str1234</transaction-name>
        <partner-name>str1234</partner-name>
        <partner-password>str1234</partner-password>
        <source-url>http://www.xsd2xml.com</source-url>
        <create-timestamp>str1234</create-timestamp>
        <response-request>0</response-request>
    </message-header>
    <ship-advice>
        <header>
            <customer-id>str1234</customer-id>
            <business-name>str1234</business-name>
            <carrier-name>str1234</carrier-name>
            <ultimate-destination-code>str1234</ultimate-destination-code>
            <packing-list-number>1234</packing-list-number>
            <release-number>str1234</release-number>
            <customer-information>
                <customer-first-name>str1234</customer-first-name>
                <customer-last-name>str1234</customer-last-name>
                <customer-middle-initial>str1234</customer-middle-initial>
                <customer-address1>str1234</customer-address1>
                <customer-address2>str1234</customer-address2>
                <customer-address3>str1234</customer-address3>
                <customer-city>str1234</customer-city>
                <customer-state>str1234</customer-state>
                <customer-post-code>str1234</customer-post-code>
                <customer-country-code>str1234</customer-country-code>
                <customer-phone1>str1234</customer-phone1>
                <customer-phone2>str1234</customer-phone2>
                <customer-fax>str1234</customer-fax>
                <customer-email>str1234</customer-email>
            </customer-information>
            <shipment-information>
                <ship-first-name>str1234</ship-first-name>
                <ship-last-name>str1234</ship-last-name>
                <ship-middle-initial>str1234</ship-middle-initial>
                <ship-address1>str1234</ship-address1>
                <ship-address2>str1234</ship-address2>
                <ship-address3>str1234</ship-address3>
                <ship-city>str1234</ship-city>
                <ship-state>str1234</ship-state>
                <ship-post-code>str1234</ship-post-code>
                <ship-country-code>str1234</ship-country-code>
                <ship-phone1>str1234</ship-phone1>
                <ship-phone2>str1234</ship-phone2>
                <ship-fax>str1234</ship-fax>
                <ship-email>str1234</ship-email>
                <ship-via>str1234</ship-via>
                <ship-request-date>str1234</ship-request-date>
                <ship-request-from>str1234</ship-request-from>
                <ship-request-warehouse>str1234</ship-request-warehouse>
            </shipment-information>
            <purchase-order-information>
                <purchase-order-number>str1234</purchase-order-number>
                <account-description>str1234</account-description>
                <purchase-order-amount>123.45</purchase-order-amount>
                <currency-code>str1234</currency-code>
                <comments>str1234</comments>
            </purchase-order-information>
            <credit-card-information>
                <credit-card-number>str1234</credit-card-number>
                <credit-card-expiration-date>str1234</credit-card-expiration-date>
                <credit-card-identification>str1234</credit-card-identification>
                <global-card-classification-code>str1234</global-card-classification-code>
                <card-holder-name>str1234</card-holder-name>
                <card-holder-address1>str1234</card-holder-address1>
                <card-holder-address2>str1234</card-holder-address2>
                <card-holder-city>str1234</card-holder-city>
                <card-holder-state>str1234</card-holder-state>
                <card-holder-post-code>str1234</card-holder-post-code>
                <card-holder-country-code>str1234</card-holder-country-code>
            </credit-card-information>
            <invoice-information>
                <invoice-number>str1234</invoice-number>
                <invoice-creation-date>str1234</invoice-creation-date>
                <terms-due-days>str1234</terms-due-days>
                <invoice-expiration-date>str1234</invoice-expiration-date>
                <terms-discount-percentage>123.45</terms-discount-percentage>
                <terms-discount-due-days>str1234</terms-discount-due-days>
                <terms-discount-expiration-date>str1234</terms-discount-expiration-date>
                <terms-description>str1234</terms-description>
                <invoice-amount>123.45</invoice-amount>
                <invoice-discount>123.45</invoice-discount>
                <currency-code>str1234</currency-code>
            </invoice-information>
            <order-header>
                <customer-order-number>str1234</customer-order-number>
                <customer-order-date>str1234</customer-order-date>
                <order-reference>str1234</order-reference>
                <order-sub-total>123.45</order-sub-total>
                <order-discount>123.45</order-discount>
                <order-tax1>123.45</order-tax1>
                <order-tax2>123.45</order-tax2>
                <order-tax3>123.45</order-tax3>
                <order-shipment-charge>123.45</order-shipment-charge>
                <order-total-net>123.45</order-total-net>
                <order-status>str1234</order-status>
                <order-type>str1234</order-type>
                <customer-channel-type>str1234</customer-channel-type>
                <customer-group-account>str1234</customer-group-account>
                <customer-seller-code>str1234</customer-seller-code>
                <user-name>str1234</user-name>
                <gift-flag>Y</gift-flag>
                <brightpoint-order-number>str1234</brightpoint-order-number>
                <warehouse-id>str1234</warehouse-id>
                <ship-date>str1234</ship-date>
                <ship-to-code>str1234</ship-to-code>
            </order-header>
        </header>
        <detail>
            <line-item>
                <line-no>str1234</line-no>
                <line-reference>str1234</line-reference>
                <item-code>str1234</item-code>
                <universal-product-code>str1234</universal-product-code>
                <product-name>str1234</product-name>
                <comments>str1234</comments>
                <ship-quantity>123.45</ship-quantity>
                <packs>str1234</packs>
                <internal-packs>str1234</internal-packs>
                <unit-of-measure>str1234</unit-of-measure>
                <sid>str1234</sid>
                <serial-list>
                    <serial-numbers>
                        <min>str1234</min>
                        <sid>str1234</sid>
                        <mdn>str1234</mdn>
                        <esn>str1234</esn>
                        <sim>str1234</sim>
                        <imei>str1234</imei>
                        <sublock1>str1234</sublock1>
                        <sublock2>str1234</sublock2>
                        <sublock3>str1234</sublock3>
                        <irdb>str1234</irdb>
                        <meid>str1234</meid>
                        <iccid>str1234</iccid>
                        <macid>str1234</macid>
                        <pesn>str1234</pesn>
                    </serial-numbers>
                </serial-list>
                <irdb>str1234</irdb>
                <market-id>str1234</market-id>
                <line-status>str1234</line-status>
                <base-price>123.45</base-price>
                <line-discount>123.45</line-discount>
                <line-tax1>123.45</line-tax1>
                <line-tax2>123.45</line-tax2>
                <line-tax3>123.45</line-tax3>
                <ship-via>str1234</ship-via>
                <bill-of-lading>str1234</bill-of-lading>
                <pallet-id>str1234</pallet-id>
                <scac>str1234</scac>
                <routing-description>str1234</routing-description>
                <container-id>str1234</container-id>
                <ownership-flag>str1234</ownership-flag>
                <special-message>
                    <special-message1>str1234</special-message1>
                    <special-message2>str1234</special-message2>
                    <special-message3>str1234</special-message3>
                    <special-message4>str1234</special-message4>
                    <special-message5>str1234</special-message5>
                </special-message>
            </line-item>
        </detail>
    </ship-advice>
    <transactionInfo />
</message>